# Generated by Django 4.0.6 on 2022-07-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=200)),
                ('data_exame', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.paciente')),
            ],
        ),
    ]
